### ISSUE TITLE
Error typing "edge"

### ISSUE THREAD

**Issue by nilvanlopes** [cspotcode/Flow.Launcher.Plugin.EdgeWorkspaces#1]
Flow Launcher version: 1.19.3
OS Version: 26100.2033
IntPtr Length: 8
x64: True

Python Path: C:\Users\pyu\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 10/21/2024 09:24:04
Exception:
Edge Workspaces Exception: 
Websites: https://github.com/cspotcode/Flow.Launcher.Plugin.EdgeWorkspaces
Author: Andrew Bradley
Version: 0.0.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: [0m[1m[31merror[0m: Uncaught (in promise) SyntaxError: No number after minus sign in JSON at position 1 (line 1 column 2)
    at [0m[1m[3mJSON.parse[0m ([0m[36m<anonymous>[0m)
    at [0m[1m[3mreadRequest[0m ([0m[36mfile:///C:/Users/pyu/AppData/Local/Temp/deno-compile-plugin.exe/Flow.Launcher.Plugin.EdgeWorkspaces/src/flow-api.ts[0m:[0m[33m2[0m:[0m[33m15[0m)
    at [0m[36mfile:///C:/Users/pyu/AppData/Local/Temp/deno-compile-plugin.exe/Flow.Launcher.Plugin.EdgeWorkspaces/main.ts[0m:[0m[33m6[0m:[0m[33m32[0m

 ---> System.IO.InvalidDataException: [0m[1m[31merror[0m: Uncaught (in promise) SyntaxError: No number after minus sign in JSON at position 1 (line 1 column 2)
    at [0m[1m[3mJSON.parse[0m ([0m[36m<anonymous>[0m)
    at [0m[1m[3mreadRequest[0m ([0m[36mfile:///C:/Users/pyu/AppData/Local/Temp/deno-compile-plugin.exe/Flow.Launcher.Plugin.EdgeWorkspaces/src/flow-api.ts[0m:[0m[33m2[0m:[0m[33m15[0m)
    at [0m[36mfile:///C:/Users/pyu/AppData/Local/Temp/deno-compile-plugin.exe/Flow.Launcher.Plugin.EdgeWorkspaces/main.ts[0m:[0m[33m6[0m:[0m[33m32[0m

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 248
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 247
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 276
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by cspotcode** [comment]
This is confusing.  `Uncaught (in promise) SyntaxError: No number after minus sign in JSON at position 1 (line 1 column 2)`

This makes it appear as though _Flow Launcher_ sent my plugin bad JSON.

I've published a new version 0.0.3 with improved logging.  Flow's plugin index has a delay picking up new versions.  Once 0.0.3 is available, we should be able to install it, try again, and get a more descriptive error to share.

**Comment by nilvanlopes** [comment]
Flow Launcher version: 1.19.3
OS Version: 26100.1742
IntPtr Length: 8
x64: True

Python Path: C:\Users\pyu\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Program Files\nodejs\node.exe
Date: 10/21/2024 16:17:51
Exception:
Edge Workspaces Exception: 
Websites: https://github.com/cspotcode/Flow.Launcher.Plugin.EdgeWorkspaces
Author: Andrew Bradley
Version: 0.0.3
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: [0m[1m[31merror[0m: Uncaught (in promise) Error: Error parsing JSON-RPC payload from Flow Launcher:
Args: ["--frozen","{\"method\":\"query\",\"parameters\":[\"\"],\"settings\":{},\"id\":0,\"error\":null}"]
Parsing error:
No number after minus sign in JSON at position 1 (line 1 column 2)
    at [0m[1m[3mreadRequest[0m ([0m[36mfile:///C:/Users/pyu/AppData/Local/Temp/deno-compile-plugin.exe/Flow.Launcher.Plugin.EdgeWorkspaces/src/flow-api.ts[0m:[0m[33m6[0m:[0m[33m11[0m)
    at [0m[36mfile:///C:/Users/pyu/AppData/Local/Temp/deno-compile-plugin.exe/Flow.Launcher.Plugin.EdgeWorkspaces/main.ts[0m:[0m[33m6[0m:[0m[33m32[0m

 ---> System.IO.InvalidDataException: [0m[1m[31merror[0m: Uncaught (in promise) Error: Error parsing JSON-RPC payload from Flow Launcher:
Args: ["--frozen","{\"method\":\"query\",\"parameters\":[\"\"],\"settings\":{},\"id\":0,\"error\":null}"]
Parsing error:
No number after minus sign in JSON at position 1 (line 1 column 2)
    at [0m[1m[3mreadRequest[0m ([0m[36mfile:///C:/Users/pyu/AppData/Local/Temp/deno-compile-plugin.exe/Flow.Launcher.Plugin.EdgeWorkspaces/src/flow-api.ts[0m:[0m[33m6[0m:[0m[33m11[0m)
    at [0m[36mfile:///C:/Users/pyu/AppData/Local/Temp/deno-compile-plugin.exe/Flow.Launcher.Plugin.EdgeWorkspaces/main.ts[0m:[0m[33m6[0m:[0m[33m32[0m

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 248
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 247
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 276
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by nilvanlopes** [comment]
don't know if help, but the powertoys run edge plugin works
![image](https://github.com/user-attachments/assets/564c4f52-22e5-4d96-866e-c57bae71ebca)

**Comment by cspotcode** [comment]
I actually based some of the code for this plugin off of the Powertoys Run plugin.

**Comment by cspotcode** [comment]
Just realized you sent an updated error.  Thanks!  The `--frozen` flag is unexpected, and I'm pretty sure this is undocumented Flow Launcher behavior.  Easy for me to fix, but I also want to get clarity from the Flow Launcher team/docs if this is intended.

**Comment by cspotcode** [comment]
Fixed in 0.0.4!  Turns out it was my fault, not Flow.  It was a problem in my CI builds which is why I didn't catch it in my local testing.
